# Generated by Django 3.0.2 on 2022-12-20 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genometeam',
            name='sample_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Person', verbose_name='sample_coordinator'),
        ),
        migrations.RemoveField(
            model_name='annotationteam',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='annotationteam',
            name='affiliation',
            field=models.ManyToManyField(to='status.Affiliation'),
        ),
        migrations.AlterField(
            model_name='annotationteam',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_team_lead', to='status.Person'),
        ),
        migrations.AlterField(
            model_name='assemblyteam',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_team_lead', to='status.Person'),
        ),
        migrations.AlterField(
            model_name='collectionteam',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_team_lead', to='status.Person'),
        ),
        migrations.AlterField(
            model_name='curationteam',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_team_lead', to='status.Person'),
        ),
        migrations.RemoveField(
            model_name='sequencingteam',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='sequencingteam',
            name='affiliation',
            field=models.ManyToManyField(to='status.Affiliation'),
        ),
        migrations.AlterField(
            model_name='sequencingteam',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_delivery', to='status.Person'),
        ),
        migrations.AlterField(
            model_name='sequencingteam',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequencing_team_lead', to='status.Person'),
        ),
        migrations.AlterField(
            model_name='sequencingteam',
            name='reception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_reception', to='status.Person'),
        ),
        migrations.RemoveField(
            model_name='submissionteam',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='submissionteam',
            name='affiliation',
            field=models.ManyToManyField(to='status.Affiliation'),
        ),
        migrations.AlterField(
            model_name='submissionteam',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_team_lead', to='status.Person'),
        ),
        migrations.CreateModel(
            name='TaxonomyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=100)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_team_lead', to='status.Person')),
            ],
        ),
        migrations.AddField(
            model_name='genometeam',
            name='taxonomy_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.TaxonomyTeam', verbose_name='taxonomy team'),
        ),
    ]
