"""
Django settings for cbp project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'deployment', 'data') # 'data' is my media folder
MEDIA_URL = '/media/'
# STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),'deployment', 'static')
STATIC_ROOT = '/home/www/resistome.cnag.cat/incredible/deployment/static'
STATIC_URL = '/static/'
CKEDITOR_UPLOAD_PATH = MEDIA_URL
CMS_COLOR_SCHEME = "light"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = ''
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['resistome.cnag.cat','resistome.cnag.es','resistome.cnag.eu','genomes.cnag.cat','genomes.cnag.es','genomes.cnag.eu','localhost','10.73.4.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dal',
    'dal_select2',
    #'allauth.socialaccount.providers.google',
    'erga',
    'django_registration',
    'status',
    'rest_framework',
    'django_filters',
    'django_tables2',
    'django_tables2_column_shifter',
    'bootstrap3',
    'bootstrap4',
    'cookielaw',
    'crispy_forms',
    'qurl_templatetag',
    'multiselectfield',
    'modelclone',
    'django_addanother',
    'django_popup_view_field',
    'tagging',
    "debug_toolbar",
    "django_cron",
    "django_ckeditor_5"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #'debug_toolbar.middleware.DebugToolbarMiddleware',
    #'maintenance_mode.middleware.MaintenanceModeMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
    ]
CRON_CLASSES = [
    "status.views.SpeciesSaveCronJob",
    "status.views.UpdateSamplesCronJob",
    "status.views.FetchEARsCronJob",
    # ...
]
ROOT_URLCONF = 'erga.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": ["/home/www/resistome.cnag.cat/cbp/erga/templates","/home/www/resistome.cnag.cat/cbp/erga/admin","/home/www/resistome.cnag.cat/cbp/erga/templates/account/","/cbp/status/templates/","/cbp/erga/templates/"],
#        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'status.context_processors.customization',
            ],
        },
    },
]

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.request',
    )

WSGI_APPLICATION = 'erga.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cbp',
        'USER': 'cbp_admin',
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'OPTIONS': {
     "init_command": "SET foreign_key_checks = 0;",
     },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    #'DEFAULT_PAGINATION_CLASS': None,
    #'PAGE_SIZE': 10,
    'PAGE_SIZE': 99999999999,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions',
    ],
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

CRISPY_TEMPLATE_PACK = 'bootstrap4'
SITE_ID = 1
ACCOUNT_LOGOUT_REDIRECT_URL="https://genomes.cnag.cat/cbp/"
DEFAULT_DOMAIN="https://genomes.cnag.cat/cbp/"
LOGIN_REDIRECT_URL = 'home'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS=7
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "https://genomes.cnag.cat/cbp/accounts/login/"
LOGIN_URL="/cbp/accounts/login/"


# EMAIL_BACKEND = 'django_o365mail.EmailBackend'
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
# O365_MAIL_CLIENT_ID = config('O365_MAIL_CLIENT_ID')
# O365_MAIL_CLIENT_SECRET = config('O365_MAIL_CLIENT_SECRET')
# O365_MAIL_TENANT_ID = config('O365_MAIL_TENANT_ID')
# O365_MAIL_ACCOUNT_KWARGS = {'token_backend': 'O365.utils.token.EnvTokenBackend'}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = False
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 25
#EMAIL_USE_TLS=True
#EMAIL_PORT=587 # also tried port 25
NOTIFICATIONS = True
ACCOUNT_FORMS = {
'signup': 'gtc.forms.CustomSignupForm',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',  # Simple formatting using str.format()
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',  # Log WARNING and ERROR messages
            'class': 'logging.FileHandler',
            'filename': "/home/talioto/logs/cbp-gtc.log",  # Change file path if needed
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'status': {  # Logger for your custom app
            'handlers': ['file'],
            'level': 'DEBUG',  # DEBUG level logs for development
            'propagate': False,
        },
        'erga': {  # Logger for your custom app
            'handlers': ['file'],
            'level': 'DEBUG',  # DEBUG level logs for development
            'propagate': False,
        },
    },
}

USE_THOUSAND_SEPARATOR = True
DATE_INPUT_FORMATS = [
    '%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', # '2006-10-25', '10/25/2006', '10/25/06'
    '%Y-%m',  # '2006-10'
    '%b %d %Y', '%b %d, %Y',            # 'Oct 25 2006', 'Oct 25, 2006'
    '%d %b %Y', '%d %b, %Y',            # '25 Oct 2006', '25 Oct, 2006'
    '%B %d %Y', '%B %d, %Y',            # 'October 25 2006', 'October 25, 2006'
    '%d %B %Y', '%d %B, %Y',            # '25 October 2006', '25 October, 2006'
]
#MAINTENANCE_MODE_IGNORE_SUPERUSER = True
GITHUB_TOKEN = config('GITHUB_TOKEN')

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', 'bulletedList', 'numberedList', '|',
            'blockQuote', 'insertTable', '|',
            'undo', 'redo'
        ],
    }
}