# Generated by Django 3.2.25 on 2026-03-10 00:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import status.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'affiliations',
            },
        ),
        migrations.CreateModel(
            name='AnnotationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'annotation teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssemblyPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pipeline name', max_length=30)),
                ('version', models.CharField(help_text='Version', max_length=10)),
                ('contigger', models.CharField(help_text='Main assembler', max_length=30)),
                ('scaffolder', models.CharField(help_text='Scaffolder (can be the same as assembler)', max_length=30)),
                ('url', models.CharField(blank=True, help_text='URL', max_length=300, null=True)),
                ('description', models.TextField(blank=True, help_text='Full description of pipeline', max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'assembly pipelines',
            },
        ),
        migrations.CreateModel(
            name='AssemblyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'assembly teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BarcodingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'barcoding teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BiobankingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('institution', models.ManyToManyField(to='status.Affiliation')),
            ],
            options={
                'verbose_name_plural': 'biobanking teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BUSCOdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(db_index=True, max_length=60)),
            ],
            options={
                'verbose_name_plural': 'BUSCO dbs',
            },
        ),
        migrations.CreateModel(
            name='BUSCOversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'BUSCO versions',
            },
        ),
        migrations.CreateModel(
            name='CollectionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'collection teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CommunityAnnotationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Community annotation teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='EnaReads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ont_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='ONT Accession')),
                ('hifi_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='HiFi Accession')),
                ('hic_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='Hi-C Accession')),
                ('short_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='Short read Accession')),
                ('rnaseq_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='RNAseq Accession')),
                ('study_accession', models.CharField(blank=True, max_length=12, null=True, verbose_name='Study')),
            ],
            options={
                'verbose_name_plural': 'ena_reads',
            },
        ),
        migrations.CreateModel(
            name='ExtractionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'extraction teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'phases',
            },
        ),
        migrations.CreateModel(
            name='Reads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ont_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='ONT Accession')),
                ('hifi_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='HiFi Accession')),
                ('hic_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='Hi-C Accession')),
                ('short_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='Short read Accession')),
                ('rnaseq_ena', models.CharField(blank=True, max_length=12, null=True, verbose_name='RNAseq Accession')),
                ('study_accession', models.CharField(blank=True, max_length=12, null=True, verbose_name='Study')),
            ],
            options={
                'verbose_name_plural': 'reads',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Recipe name')),
                ('ont_target', models.BigIntegerField(blank=True, null=True, verbose_name='ONT target')),
                ('hifi_target', models.BigIntegerField(blank=True, null=True, verbose_name='HiFi target')),
                ('hic_target', models.BigIntegerField(blank=True, null=True, verbose_name='Hi-C target')),
                ('short_target', models.BigIntegerField(blank=True, null=True, verbose_name='Short read target')),
                ('rna_target', models.BigIntegerField(blank=True, null=True, verbose_name='RNA-seq PE target')),
            ],
            options={
                'verbose_name_plural': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copo_status', models.CharField(choices=[('Not submitted', 'Not submitted'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Not submitted', help_text='COPO status', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('sample_provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_provider_email', models.CharField(blank=True, max_length=150, null=True)),
                ('mta1', models.BooleanField(default=False, verbose_name='MTA 1: Seq Centers')),
                ('mta2', models.BooleanField(default=False, verbose_name='MTA 2: LIB leftovers')),
                ('barcoding_status', models.CharField(choices=[('DNA_BARCODING_TO_BE_PERFORMED', 'DNA_BARCODING_TO_BE_PERFORMED'), ('DNA_BARCODING_COMPLETED', 'DNA_BARCODING_COMPLETED'), ('DNA_BARCODING_EXEMPT', 'DNA_BARCODING_EXEMPT'), ('DNA_BARCODING_FAILED', 'DNA_BARCODING_FAILED')], default='DNA_BARCODING_TO_BE_PERFORMED', help_text='Barcoding Status', max_length=30)),
                ('barcoding_results', models.CharField(blank=True, max_length=200, null=True)),
                ('sampling_month', status.models.MonthDateField(blank=True, null=True)),
                ('deadline_manifest_sharing', models.DateField(blank=True, null=True)),
                ('deadline_manifest_acceptance', models.DateField(blank=True, null=True)),
                ('deadline_sample_shipment', models.DateField(blank=True, null=True)),
                ('sampling_delay', models.BooleanField(default=False, verbose_name='Delayed sample')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.country', verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'collection',
                'ordering': ['species'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('statement', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'statements',
            },
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'subprojects',
            },
        ),
        migrations.CreateModel(
            name='TaxonClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaxonFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taxon_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonclass', verbose_name='Kingdom')),
            ],
            options={
                'verbose_name_plural': 'families',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaxonKingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'kingdoms',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('lead', models.BooleanField(default=False)),
                ('orcid', models.CharField(blank=True, max_length=60, null=True, verbose_name='ORCID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('affiliation', models.ManyToManyField(to='status.Affiliation')),
                ('roles', models.ManyToManyField(default='other', to='status.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoucheringTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchering_team_lead', to='status.userprofile')),
                ('members', models.ManyToManyField(blank=True, null=True, to='status.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'vouchering teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaxonPhylum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taxon_kingdom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonkingdom', verbose_name='Kingdom')),
            ],
            options={
                'verbose_name_plural': 'phyla',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaxonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taxon_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonclass', verbose_name='Kingdom')),
                ('taxon_kingdom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonkingdom', verbose_name='Kingdom')),
                ('taxon_phylum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonphylum', verbose_name='Kingdom')),
            ],
            options={
                'verbose_name_plural': 'orders',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_team_lead', to='status.userprofile')),
                ('members', models.ManyToManyField(blank=True, null=True, to='status.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'taxonomy teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaxonGenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taxon_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonclass', verbose_name='Kingdom')),
                ('taxon_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonfamily', verbose_name='Kingdom')),
                ('taxon_kingdom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonkingdom', verbose_name='Kingdom')),
                ('taxon_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonorder', verbose_name='Kingdom')),
                ('taxon_phylum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonphylum', verbose_name='Kingdom')),
            ],
            options={
                'verbose_name_plural': 'genera',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='taxon_kingdom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonkingdom', verbose_name='Kingdom'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='taxon_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonorder', verbose_name='Kingdom'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='taxon_phylum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonphylum', verbose_name='Kingdom'),
        ),
        migrations.AddField(
            model_name='taxonclass',
            name='taxon_kingdom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonkingdom', verbose_name='Kingdom'),
        ),
        migrations.AddField(
            model_name='taxonclass',
            name='taxon_phylum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.taxonphylum', verbose_name='Kingdom'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('subproject', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.subproject', verbose_name='subproject')),
            ],
            options={
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TargetSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_species', models.CharField(blank=True, max_length=201, null=True)),
                ('scientific_name', models.CharField(blank=True, db_index=True, max_length=201, null=True)),
                ('tolid_prefix', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('chromosome_number', models.IntegerField(blank=True, null=True)),
                ('haploid_number', models.IntegerField(blank=True, null=True)),
                ('ploidy', models.IntegerField(blank=True, null=True)),
                ('taxon_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('c_value', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='C-value')),
                ('genome_size', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GoaT Size Estimate')),
                ('genome_size_update', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Updated Genome Size')),
                ('genome_size_update_evidence', models.CharField(blank=True, max_length=100, null=True, verbose_name='Evidence for Estimated Size')),
                ('subspecies_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subspecies')),
                ('goat_target_list_status', models.CharField(choices=[('waiting_list', 'waiting_list'), ('none', 'none'), ('long_list', 'long_list'), ('other_priority', 'other_priority'), ('family_representative', 'family_representative'), ('removed', 'removed')], default='waiting_list', help_text='Target List Status', max_length=30, verbose_name='target_list_status')),
                ('goat_sequencing_status', models.CharField(blank=True, choices=[('none', 'none'), ('in_collection', 'in_collection'), ('sample_collected', 'sample_collected'), ('sample_acquired', 'sample_acquired'), ('data_generation', 'data_generation'), ('in_assembly', 'in_assembly'), ('insdc_open', 'insdc_open'), ('published', 'published'), ('cancelled', 'cancelled'), ('paused', 'paused')], default='none', help_text='Sequencing Status', max_length=30, null=True, verbose_name='GoaT Sequencing Status')),
                ('gss_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('copo_status', models.CharField(choices=[('Not submitted', 'Not submitted'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Not submitted', help_text='COPO status', max_length=20)),
                ('synonym', models.CharField(blank=True, max_length=100, null=True, verbose_name='Synonym')),
                ('publication_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Publication ID')),
                ('iucn_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='IUCN Assessment')),
                ('iucn_url', models.URLField(blank=True, max_length=400, null=True, verbose_name='IUCN Page')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('goat', models.BooleanField(default=False)),
                ('ranking', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Ranking')),
                ('taxon_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.taxonclass', verbose_name='Class')),
                ('taxon_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.taxonfamily', verbose_name='Family')),
                ('taxon_genus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.taxongenus', verbose_name='Genus')),
                ('taxon_kingdom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.taxonkingdom', verbose_name='Kingdom')),
                ('taxon_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.taxonorder', verbose_name='Order')),
                ('taxon_phylum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.taxonphylum', verbose_name='Phylum')),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=201, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.targetspecies', verbose_name='Genus/species')),
            ],
            options={
                'verbose_name_plural': 'synonyms',
            },
        ),
        migrations.CreateModel(
            name='SubSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('taxon_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspecies_rel', to='status.targetspecies', verbose_name='Genus/species')),
            ],
            options={
                'verbose_name_plural': 'subspecies',
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(help_text='Process', max_length=30)),
                ('status', models.CharField(help_text='Status', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.targetspecies', verbose_name='species')),
            ],
            options={
                'verbose_name_plural': 'status updates',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_id', models.CharField(db_index=True, help_text='Internal Specimen ID', max_length=100)),
                ('tolid', models.CharField(default='No ToLID', help_text='Registered ToLID for the Specimen', max_length=20)),
                ('biosampleAccession', models.CharField(blank=True, help_text='BioSample Accession', max_length=20, null=True, verbose_name='Specimen BioSample')),
                ('sample_coordinator', models.CharField(blank=True, help_text='Sample coordinator', max_length=120, null=True)),
                ('tissue_removed_for_biobanking', models.BooleanField(default=False)),
                ('tissue_voucher_id_for_biobanking', models.CharField(blank=True, max_length=500, null=True)),
                ('proxy_tissue_voucher_id_for_biobanking', models.CharField(blank=True, max_length=2000, null=True)),
                ('tissue_for_biobanking', models.CharField(blank=True, max_length=100, null=True)),
                ('dna_removed_for_biobanking', models.BooleanField(default=False)),
                ('dna_voucher_id_for_biobanking', models.CharField(blank=True, max_length=200, null=True)),
                ('voucher_id', models.CharField(blank=True, help_text='Voucher ID', max_length=2000, null=True)),
                ('proxy_voucher_id', models.CharField(blank=True, help_text='Proxy voucher ID', max_length=2000, null=True)),
                ('voucher_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('proxy_voucher_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('voucher_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('ircc', models.URLField(blank=True, max_length=400, null=True, verbose_name='IRCC')),
                ('biobanking_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.biobankingteam', verbose_name='biobanking team')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.samplecollection', verbose_name='Collection')),
                ('nagoya_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.statement', verbose_name='legal statement')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimen_rel', to='status.targetspecies', verbose_name='species')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('gal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_team_lead', to='status.userprofile')),
                ('members', models.ManyToManyField(blank=True, null=True, to='status.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'sequencing teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_seq_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Received', 'Received'), ('Prep', 'Prep'), ('Extracted', 'Extracted'), ('Sequencing', 'Sequencing'), ('TopUp', 'TopUp'), ('External', 'External'), ('Submitted', 'Submitted'), ('Done', 'Done'), ('Issue', 'Issue'), ('Abandoned', 'Abandoned')], default='Waiting', help_text='Status', max_length=20)),
                ('short_seq_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Received', 'Received'), ('Prep', 'Prep'), ('Extracted', 'Extracted'), ('Sequencing', 'Sequencing'), ('TopUp', 'TopUp'), ('External', 'External'), ('Submitted', 'Submitted'), ('Done', 'Done'), ('Issue', 'Issue'), ('Abandoned', 'Abandoned')], default='Waiting', help_text='Status', max_length=20)),
                ('hic_seq_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Received', 'Received'), ('Prep', 'Prep'), ('Extracted', 'Extracted'), ('Sequencing', 'Sequencing'), ('TopUp', 'TopUp'), ('External', 'External'), ('Submitted', 'Submitted'), ('Done', 'Done'), ('Issue', 'Issue'), ('Abandoned', 'Abandoned')], default='Waiting', help_text='Status', max_length=20)),
                ('rna_seq_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Received', 'Received'), ('Prep', 'Prep'), ('Extracted', 'Extracted'), ('Sequencing', 'Sequencing'), ('TopUp', 'TopUp'), ('External', 'External'), ('Submitted', 'Submitted'), ('Done', 'Done'), ('Issue', 'Issue'), ('Abandoned', 'Abandoned')], default='Waiting', help_text='Status', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('species_umbrella', models.CharField(blank=True, max_length=12, null=True, verbose_name='Species Umbrella Accession')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.phase', verbose_name='Phase')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.recipe', to_field='name', verbose_name='Recipe')),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_rel', to='status.targetspecies', verbose_name='species')),
            ],
            options={
                'verbose_name_plural': 'sequencing',
            },
        ),
        migrations.CreateModel(
            name='SampleHandlingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_handling_team_lead', to='status.userprofile')),
                ('members', models.ManyToManyField(blank=True, null=True, to='status.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'sample handling teams',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_rel', to='status.targetspecies', verbose_name='species'),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='subproject',
            field=models.ManyToManyField(blank=True, default=[0], null=True, to='status.Subproject'),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.task', verbose_name='Task'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copo_id', models.CharField(blank=True, help_text='COPO ID', max_length=30, null=True, verbose_name='CopoID')),
                ('biosampleAccession', models.CharField(blank=True, help_text='BioSample Accession', max_length=20, null=True, verbose_name='BioSample')),
                ('sampleDerivedFrom', models.CharField(blank=True, help_text='BioSample Derived From', max_length=20, null=True, verbose_name='SampleDerivedFrom')),
                ('sampleSameAs', models.CharField(blank=True, help_text='BioSample Same As', max_length=20, null=True, verbose_name='SampleSameAs')),
                ('barcode', models.CharField(blank=True, help_text='Tube barcode', max_length=50, null=True)),
                ('purpose_of_specimen', models.CharField(blank=True, help_text='Purpose', max_length=30, null=True)),
                ('gal', models.CharField(blank=True, help_text='GAL', max_length=120, null=True, verbose_name='GAL')),
                ('gal_sample_id', models.CharField(blank=True, help_text='GAL Sample ID', max_length=200, null=True)),
                ('collector_sample_id', models.CharField(blank=True, help_text='Collector Sample ID', max_length=200, null=True)),
                ('tube_or_well_id', models.CharField(blank=True, help_text='Tube or Well ID', max_length=200, null=True)),
                ('corrected_id', models.CharField(blank=True, help_text='Corrected ID', max_length=200, null=True)),
                ('copo_date', models.CharField(blank=True, help_text='COPO Time Updated', max_length=50, null=True, verbose_name='date')),
                ('copo_status', models.CharField(blank=True, help_text='COPO Status', max_length=30, null=True, verbose_name='Status')),
                ('leftover', models.CharField(choices=[('None', 'None'), ('DNA', 'DNA'), ('Tissue', 'Tissue'), ('Both', 'Both')], default='None', help_text='Leftover sample', max_length=20)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('suppressed', models.BooleanField(default=False)),
                ('leftover_biobanking_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.biobankingteam', verbose_name='biobanking team')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.targetspecies', verbose_name='species')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.specimen', verbose_name='Specimen')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_type', models.CharField(choices=[('ONT', 'ONT'), ('HiFi', 'HiFi'), ('Illumina', 'Illumina'), ('HiC', 'HiC'), ('RNA', 'RNA')], default='ONT', help_text='Read type', max_length=15)),
                ('seq_yield', models.BigIntegerField(blank=True, null=True, verbose_name='yield')),
                ('read_n50', models.BigIntegerField(blank=True, null=True, verbose_name='n50')),
                ('read_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='read quality')),
                ('forward_filename', models.CharField(default='', help_text='Forward read filename', max_length=200)),
                ('forward_md5sum', models.CharField(blank=True, help_text='Forward read md5sum', max_length=32, null=True)),
                ('reverse_filename', models.CharField(blank=True, help_text='Forward read filename', max_length=200, null=True)),
                ('reverse_md5sum', models.CharField(blank=True, help_text='Forward read md5sum', max_length=32, null=True)),
                ('native_filename', models.CharField(blank=True, help_text='Forward read filename', max_length=200, null=True)),
                ('native_md5sum', models.CharField(blank=True, help_text='Forward read md5sum', max_length=32, null=True)),
                ('sample', models.CharField(blank=True, help_text='Sample(s)', max_length=200, null=True)),
                ('tube_or_well_id', models.CharField(blank=True, help_text='Tube or Well ID', max_length=32, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.sequencing', verbose_name='Sequencing project')),
                ('reads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_set', related_query_name='run_set', to='status.reads', verbose_name='Reads aggregate view')),
            ],
            options={
                'verbose_name_plural': 'runs',
            },
        ),
        migrations.AddField(
            model_name='reads',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.sequencing', verbose_name='Sequencing project'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(help_text='DOI', max_length=50)),
                ('title', models.CharField(help_text='Title', max_length=250)),
                ('journal', models.CharField(help_text='Journal', max_length=100)),
                ('date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2026)])),
                ('pmcid', models.CharField(help_text='PMCID', max_length=30)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_rel', to='status.targetspecies', verbose_name='species')),
            ],
            options={
                'verbose_name_plural': 'publications',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('orcid', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('affiliation', models.ManyToManyField(blank=True, null=True, to='status.Affiliation')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='HiCTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('gal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hic_team_lead', to='status.userprofile')),
                ('members', models.ManyToManyField(blank=True, null=True, to='status.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'hic teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GenomeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.annotationteam', verbose_name='annotation team')),
                ('assembly_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.assemblyteam', verbose_name='assembly team')),
                ('barcoding_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.barcodingteam', verbose_name='barcoding team')),
                ('biobanking_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.biobankingteam', verbose_name='biobanking team')),
                ('collection_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.collectionteam', verbose_name='collection team')),
                ('community_annotation_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.communityannotationteam', verbose_name='community annotation team')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.person', verbose_name='coordinator')),
                ('extraction_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.extractionteam', verbose_name='nucleic acid extraction team')),
                ('hic_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.hicteam', verbose_name='Hi-C team')),
                ('sample_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.userprofile', verbose_name='sample_coordinator')),
                ('sample_handling_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.samplehandlingteam', verbose_name='sample handling team')),
                ('sequencing_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.sequencingteam', verbose_name='sequencing team')),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gt_rel', to='status.targetspecies', verbose_name='species')),
                ('taxonomy_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.taxonomyteam', verbose_name='taxonomy team')),
                ('vouchering_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.voucheringteam', verbose_name='vouchering team')),
            ],
            options={
                'verbose_name_plural': 'genome teams',
            },
        ),
        migrations.CreateModel(
            name='FromManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_collectors', models.CharField(blank=True, help_text='Collectors', max_length=120, null=True)),
                ('sample_collector_affiliations', models.CharField(blank=True, help_text='Collector affiliations', max_length=120, null=True)),
                ('sample_collector_orcids', models.CharField(blank=True, help_text='Collector ORCIDs', max_length=120, null=True)),
                ('sample_identifiers', models.CharField(blank=True, help_text='Identifiers', max_length=120, null=True)),
                ('sample_identifier_affiliations', models.CharField(blank=True, help_text='Identifier affiliations', max_length=120, null=True)),
                ('sample_preservers', models.CharField(blank=True, help_text='Preservers', max_length=120, null=True)),
                ('sample_preserver_affiliations', models.CharField(blank=True, help_text='Preserver affiliations', max_length=120, null=True)),
                ('sample_coordinators', models.CharField(blank=True, help_text='Sample coordinators', max_length=120, null=True)),
                ('sample_coordinators_affiliations', models.CharField(blank=True, help_text='Sample coordinator affiliations', max_length=120, null=True)),
                ('sample_coordinators_orcids', models.CharField(blank=True, help_text='Sample coordinator ORCIDs', max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('collector', models.ManyToManyField(blank=True, null=True, related_name='collector_rel', to='status.Person')),
                ('coordinator', models.ManyToManyField(blank=True, null=True, related_name='coordinator_rel', to='status.Person')),
                ('identifier', models.ManyToManyField(blank=True, null=True, related_name='identifier_rel', to='status.Person')),
                ('preserver', models.ManyToManyField(blank=True, null=True, related_name='preserver_rel', to='status.Person')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_roles_rel', to='status.specimen', unique=True, verbose_name='specimen')),
            ],
            options={
                'verbose_name_plural': 'manifest roles',
            },
        ),
        migrations.AddField(
            model_name='extractionteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_team_lead', to='status.userprofile'),
        ),
        migrations.AddField(
            model_name='extractionteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='status.UserProfile'),
        ),
        migrations.CreateModel(
            name='EnaRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_type', models.CharField(choices=[('ONT', 'ONT'), ('HiFi', 'HiFi'), ('Illumina', 'Illumina'), ('HiC', 'HiC'), ('RNA', 'RNA')], default='ONT', help_text='Read type', max_length=15)),
                ('seq_yield', models.BigIntegerField(default=0, verbose_name='yield')),
                ('num_reads', models.BigIntegerField(default=0, verbose_name='Num reads')),
                ('biosample_accession', models.CharField(blank=True, max_length=16, verbose_name='Biosample Accession')),
                ('run_accession', models.CharField(max_length=16, unique=True, verbose_name='Run Accession')),
                ('experiment_accession', models.CharField(max_length=16, verbose_name='Experiment Accession')),
                ('study_accession', models.CharField(max_length=16, verbose_name='Study Accession')),
                ('library_construction_protocol', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Library Protocol')),
                ('submitted_md5', models.CharField(blank=True, max_length=70, null=True, verbose_name='md5')),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.sequencing', verbose_name='Sequencing project')),
                ('reads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ena_run_set', related_query_name='ena_run_set', to='status.enareads', verbose_name='Reads aggregate view')),
            ],
            options={
                'verbose_name_plural': 'ena_runs',
            },
        ),
        migrations.AddField(
            model_name='enareads',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.sequencing', verbose_name='Sequencing project'),
        ),
        migrations.CreateModel(
            name='CurationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curation_team_lead', to='status.userprofile')),
                ('members', models.ManyToManyField(blank=True, null=True, to='status.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'curation teams',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Curation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Curating', 'Curating'), ('Done', 'Done'), ('Sent', 'Sent'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.targetspecies', verbose_name='species')),
            ],
            options={
                'verbose_name_plural': 'curation',
            },
        ),
        migrations.AddField(
            model_name='communityannotationteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_annotation_team_lead', to='status.userprofile'),
        ),
        migrations.AddField(
            model_name='communityannotationteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='status.UserProfile'),
        ),
        migrations.CreateModel(
            name='CommunityAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Annotating', 'Annotating'), ('Done', 'Done'), ('Submitted', 'Submitted'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.targetspecies', verbose_name='species')),
            ],
        ),
        migrations.CreateModel(
            name='CommonNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.targetspecies', verbose_name='Genus/species')),
            ],
            options={
                'verbose_name_plural': 'common names',
            },
        ),
        migrations.AddField(
            model_name='collectionteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_team_lead', to='status.userprofile'),
        ),
        migrations.AddField(
            model_name='collectionteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='status.UserProfile'),
        ),
        migrations.AddField(
            model_name='biobankingteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biobanking_team_lead', to='status.userprofile'),
        ),
        migrations.AddField(
            model_name='biobankingteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='status.UserProfile'),
        ),
        migrations.AddField(
            model_name='barcodingteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcoding_team_lead', to='status.userprofile'),
        ),
        migrations.AddField(
            model_name='barcodingteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='status.UserProfile'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.userprofile', verbose_name='author')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.targetspecies', verbose_name='species')),
            ],
        ),
        migrations.AddField(
            model_name='assemblyteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_team_lead', to='status.userprofile'),
        ),
        migrations.AddField(
            model_name='assemblyteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='status.UserProfile'),
        ),
        migrations.CreateModel(
            name='AssemblyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Assembling', 'Assembling'), ('Contigs', 'Contigs'), ('Scaffolding', 'Scaffolding'), ('Scaffolds', 'Scaffolds'), ('Curating', 'Curating'), ('Done', 'Done'), ('UnderReview', 'UnderReview'), ('Approved', 'Approved'), ('Submitted', 'Submitted'), ('Issue', 'Issue'), ('Abandoned', 'Abandoned')], default='Waiting', help_text='Status', max_length=12)),
                ('genome_size_estimate', models.BigIntegerField(blank=True, null=True, verbose_name='Genome Size Estimate')),
                ('note', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('assembly_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_rel', to='status.targetspecies', verbose_name='species')),
            ],
            options={
                'verbose_name_plural': 'assembly projects',
            },
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('options', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Main options if not default')),
                ('type', models.CharField(choices=[('Primary', 'Primary'), ('Alternate', 'Alternate'), ('Hap1', 'Phased Haplotype 1'), ('Hap2', 'Phased Haplotype 2'), ('Maternal', 'Trio-phased Maternal'), ('Paternal', 'Trio-phased Paternal'), ('MT', 'Mitogenome'), ('Chloroplast', 'Chloroplast'), ('Endosymbiont', 'Endosymbiont')], default='Primary', help_text='Type of assembly', max_length=20)),
                ('span', models.BigIntegerField(blank=True, null=True, verbose_name='Assembly span')),
                ('contig_n50', models.BigIntegerField(blank=True, null=True, verbose_name='Contig N50')),
                ('scaffold_n50', models.BigIntegerField(blank=True, null=True, verbose_name='Scaffold N50')),
                ('chromosome_level', models.NullBooleanField(verbose_name='Chr level')),
                ('percent_placed', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Pct. placed')),
                ('busco', models.CharField(blank=True, max_length=60, null=True, verbose_name='BUSCO')),
                ('qv', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='QV')),
                ('report', models.URLField(blank=True, max_length=400, null=True)),
                ('accession', models.CharField(blank=True, max_length=12, null=True, verbose_name='Project Accession')),
                ('gca', models.CharField(blank=True, max_length=20, null=True, verbose_name='GCA')),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('busco_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.buscodb', verbose_name='BUSCO db')),
                ('busco_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.buscoversion', verbose_name='BUSCO version')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.assemblypipeline', verbose_name='Assembly pipeline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.assemblyproject', verbose_name='Assembly project')),
            ],
            options={
                'verbose_name_plural': 'assemblies',
            },
        ),
        migrations.AddField(
            model_name='annotationteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_team_lead', to='status.userprofile'),
        ),
        migrations.AddField(
            model_name='annotationteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='status.UserProfile'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Annotating', 'Annotating'), ('Done', 'Done'), ('Submitted', 'Submitted'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('ensembl', models.URLField(blank=True, max_length=400, null=True, verbose_name='Ensembl Rapid')),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.targetspecies', verbose_name='species')),
            ],
            options={
                'verbose_name_plural': 'annotation',
            },
        ),
    ]
