# Generated by Django 3.2.25 on 2026-04-29 14:34

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2000, null=True)),
                ('logo_filename', models.CharField(blank=True, max_length=100, null=True)),
                ('link1_url', models.CharField(blank=True, max_length=100, null=True)),
                ('link1_filename', models.CharField(blank=True, max_length=100, null=True)),
                ('link2_url', models.CharField(blank=True, max_length=100, null=True)),
                ('link2_filename', models.CharField(blank=True, max_length=100, null=True)),
                ('link3_url', models.CharField(blank=True, max_length=100, null=True)),
                ('link3_filename', models.CharField(blank=True, max_length=100, null=True)),
                ('show_production_by_center', models.BooleanField(default=False)),
                ('show_milestones', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'customizations',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calling_score',
            field=models.IntegerField(default=1000, verbose_name='Calling score'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_group',
            field=models.CharField(blank=True, help_text='Short name for your research group or lab (e.g. PI surname). Used for reviewer conflict-of-interest checks.', max_length=100, null=True, verbose_name='Research group'),
        ),
    ]
