# Generated by Django 3.2.25 on 2026-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetspecies',
            name='goat_sequencing_status',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('in_collection', 'in_collection'), ('sample_collected', 'sample_collected'), ('sample_acquired', 'sample_acquired'), ('data_generation', 'data_generation'), ('in_assembly', 'in_assembly'), ('insdc_submitted', 'insdc_submitted'), ('insdc_open', 'insdc_open'), ('published', 'published'), ('cancelled', 'cancelled'), ('paused', 'paused')], default='none', help_text='Sequencing Status', max_length=30, null=True, verbose_name='GoaT Sequencing Status'),
        ),
    ]
