# Generated by Django 3.0.2 on 2023-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20230112_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblyteam',
            old_name='contact',
            new_name='lead',
        ),
        migrations.RenameField(
            model_name='collectionteam',
            old_name='coordinator',
            new_name='lead',
        ),
        migrations.RenameField(
            model_name='taxonomyteam',
            old_name='coordinator',
            new_name='lead',
        ),
        migrations.RemoveField(
            model_name='sequencingteam',
            name='delivery',
        ),
        migrations.AddField(
            model_name='annotationteam',
            name='members',
            field=models.ManyToManyField(to='status.Person'),
        ),
        migrations.AddField(
            model_name='assemblyteam',
            name='members',
            field=models.ManyToManyField(to='status.Person'),
        ),
        migrations.AddField(
            model_name='submissionteam',
            name='members',
            field=models.ManyToManyField(to='status.Person'),
        ),
        migrations.RemoveField(
            model_name='annotationteam',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='annotationteam',
            name='affiliation',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='sequencingteam',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='sequencingteam',
            name='affiliation',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='submissionteam',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='submissionteam',
            name='affiliation',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
    ]
