# Generated by Django 3.2.25 on 2026-04-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20260429_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Research group name')),
            ],
            options={
                'verbose_name_plural': 'research groups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Your research group or lab (e.g. PI surname). Used for conflict-of-interest checks in the EAR review process.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.researchgroup', verbose_name='Research group'),
        ),
    ]
