# Generated by Django 3.2.25 on 2026-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_targetspecies_goat_sequencing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='goat_subproject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
