# Generated by Django 3.2.25 on 2026-04-29 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0004_create_ear_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='EARReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_pdf', models.FileField(upload_to='ear_pdfs/', verbose_name='EAR PDF')),
                ('pretext_file', models.FileField(blank=True, null=True, upload_to='pretext/', verbose_name='Pretext map')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('reviewer_approved', 'Approved by reviewer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined')], default='submitted', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ear_review', to='status.assemblyproject', verbose_name='Assembly project')),
            ],
            options={
                'verbose_name': 'EAR review',
                'verbose_name_plural': 'EAR reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EARReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ear_reviewer_additions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.earreview')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ear_reviewer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'reviewer')},
            },
        ),
        migrations.AddField(
            model_name='earreview',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='ear_reviews', through='status.EARReviewer', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='earreview',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ear_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by'),
        ),
        migrations.AddField(
            model_name='earreview',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ear_supervised', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.CreateModel(
            name='EARComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ear_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='status.earcomment', verbose_name='Reply to')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='status.earreview', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'EAR comment',
                'verbose_name_plural': 'EAR comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EARAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ear_attachments/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='status.earcomment', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'EAR attachment',
                'verbose_name_plural': 'EAR attachments',
            },
        ),
    ]
