# Generated by Django 3.2.25 on 2026-05-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0004_customization_goat_subproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='EARReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_pdf', models.FileField(upload_to='ear_pdfs/', verbose_name='EAR PDF')),
                ('pretext_file', models.FileField(blank=True, null=True, upload_to='pretext/', verbose_name='Pretext map')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('reviewer_approved', 'Approved by reviewer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined')], default='submitted', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ear_review', to='status.assemblyproject', verbose_name='Assembly project')),
            ],
            options={
                'verbose_name': 'EAR review',
                'verbose_name_plural': 'EAR reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Research group name')),
            ],
            options={
                'verbose_name_plural': 'research groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customization',
            name='pill_palette',
            field=models.CharField(choices=[('original', 'Original (current greens)'), ('bold', 'Bold Stepped (two yellows → mint → solid green)'), ('tonal', 'Tonal (all pastel tints, rose-pink errors)'), ('erga', 'ERGA Classic (solid fills, white text, teal/cyan)')], default='original', help_text='Colour scheme for all status pills across the site.', max_length=20),
        ),
        migrations.AddField(
            model_name='customization',
            name='show_copo',
            field=models.BooleanField(default=True, help_text='Show COPO status columns and filters in the views.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calling_score',
            field=models.IntegerField(default=1000, verbose_name='Calling score'),
        ),
        migrations.CreateModel(
            name='EARReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ear_reviewer_additions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.earreview')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ear_reviewer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'reviewer')},
            },
        ),
        migrations.AddField(
            model_name='earreview',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='ear_reviews', through='status.EARReviewer', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='earreview',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ear_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by'),
        ),
        migrations.AddField(
            model_name='earreview',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ear_supervised', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.CreateModel(
            name='EARComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ear_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='status.earcomment', verbose_name='Reply to')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='status.earreview', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'EAR comment',
                'verbose_name_plural': 'EAR comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EARAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ear_attachments/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='status.earcomment', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'EAR attachment',
                'verbose_name_plural': 'EAR attachments',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Your research group or lab (e.g. PI surname). Used for conflict-of-interest checks in the EAR review process.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.researchgroup', verbose_name='Research group'),
        ),
        migrations.CreateModel(
            name='EARAssignmentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reviewer', 'Reviewer'), ('supervisor', 'Supervisor')], max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='status.earreview', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ear_invites', to=settings.AUTH_USER_MODEL, verbose_name='Invitee')),
            ],
            options={
                'verbose_name': 'EAR assignment invite',
                'verbose_name_plural': 'EAR assignment invites',
                'ordering': ['-created_at'],
                'unique_together': {('review', 'user', 'role')},
            },
        ),
    ]
