# Generated by Django 3.2.25 on 2026-05-05 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0005_auto_20260429_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='EARAssignmentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reviewer', 'Reviewer'), ('supervisor', 'Supervisor')], max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='status.earreview', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ear_invites', to=settings.AUTH_USER_MODEL, verbose_name='Invitee')),
            ],
            options={
                'verbose_name': 'EAR assignment invite',
                'verbose_name_plural': 'EAR assignment invites',
                'ordering': ['-created_at'],
                'unique_together': {('review', 'user', 'role')},
            },
        ),
    ]
