# Generated by Django 3.2.25 on 2026-05-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_pdf_versions(apps, schema_editor):
    EARReview = apps.get_model('status', 'EARReview')
    EARPdfVersion = apps.get_model('status', 'EARPdfVersion')
    qs = (EARReview.objects
          .exclude(ear_pdf='')
          .exclude(ear_pdf__isnull=True)
          .exclude(submitted_by__isnull=True))
    for review in qs:
        EARPdfVersion.objects.create(
            review=review,
            file=review.ear_pdf,
            uploaded_by=review.submitted_by,
            uploaded_at=review.created_at,
            is_current=True,
            note='',
        )


def reverse_backfill(apps, schema_editor):
    EARPdfVersion = apps.get_model('status', 'EARPdfVersion')
    EARPdfVersion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0006_earreview_contig_level_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='earcomment',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EARPdfVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ear_pdfs/versions/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('is_current', models.BooleanField(default=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_versions', to='status.earreview', verbose_name='Review')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ear_pdf_versions', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'EAR PDF version',
                'verbose_name_plural': 'EAR PDF versions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RunPython(backfill_pdf_versions, reverse_code=reverse_backfill),
    ]
