# Generated by Django 3.2.25 on 2026-05-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_backfill_ear_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='show_copo',
            field=models.BooleanField(default=True, help_text='Show COPO status columns and filters in the views.'),
        ),
    ]
