# Generated by Django 3.0.2 on 2023-01-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20230113_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcodingteam',
            old_name='affiliation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='collectionteam',
            old_name='affiliation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='samplehandlingteam',
            old_name='affiliation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taxonomyteam',
            old_name='affiliation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='voucheringteam',
            old_name='affiliation',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='annotationteam',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='assemblyteam',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='communityannotationteam',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='curationteam',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='extractionteam',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='sequencingteam',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='submissionteam',
            name='affiliation',
        ),
        migrations.AlterField(
            model_name='annotationteam',
            name='name',
            field=models.CharField(default='TEAM', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assemblyteam',
            name='name',
            field=models.CharField(default='TEAM', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communityannotationteam',
            name='name',
            field=models.CharField(default='TEAM', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curationteam',
            name='name',
            field=models.CharField(default='TEAM', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractionteam',
            name='name',
            field=models.CharField(default='TEAM', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequencingteam',
            name='name',
            field=models.CharField(default='TEAM', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionteam',
            name='name',
            field=models.CharField(default='TEAM', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Person', verbose_name='author')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.TargetSpecies', verbose_name='species')),
            ],
        ),
    ]
