# Generated by Django 3.2.25 on 2026-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20260507_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='earcomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earcomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customization',
            name='pill_palette',
            field=models.CharField(choices=[('bold', 'Bold Stepped (two yellows → mint → solid green)'), ('tonal', 'Tonal (all pastel tints, rose-pink errors)'), ('erga', 'ERGA Classic (solid fills, white text, teal/cyan)'), ('meadow', 'Meadow Green (lime-cream → ocean-mist → baltic-blue)')], default='meadow', help_text='Colour scheme for all status pills across the site.', max_length=20),
        ),
    ]
