# Generated by Django 3.2.25 on 2026-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_customization_show_copo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='pill_palette',
            field=models.CharField(choices=[('original', 'Original (current greens)'), ('bold', 'Bold Stepped (two yellows → mint → solid green)'), ('tonal', 'Tonal (all pastel tints, rose-pink errors)'), ('erga', 'ERGA Classic (solid fills, white text, teal/cyan)')], default='original', help_text='Colour scheme for all status pills across the site.', max_length=20),
        ),
    ]
