# Generated by Django 3.2.25 on 2026-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_pill_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='earreview',
            name='contig_level_assembly',
            field=models.BooleanField(default=False, help_text='Check if this is a contig-level assembly (no Hi-C scaffolding). Pretext map upload is then optional.', verbose_name='Contig-level assembly'),
        ),
    ]
