# Generated by Django 3.0.2 on 2023-02-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0029_auto_20230201_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sample_coordinator',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='species',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='specimen_id',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='tolid',
        ),
        migrations.AddField(
            model_name='sample',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Specimen', verbose_name='Specimen'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='dna_removed_for_biobanking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specimen',
            name='dna_voucher_id_for_biobanking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='proxy_voucher_id',
            field=models.CharField(blank=True, help_text='Proxy voucher ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='proxy_voucher_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='sample_coordinator',
            field=models.CharField(blank=True, help_text='Sample coordinator', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.TargetSpecies', verbose_name='species'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='tissue_for_biobanking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='tissue_removed_for_biobanking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specimen',
            name='tissue_voucher_id_for_biobanking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='voucher_id',
            field=models.CharField(blank=True, help_text='Voucher ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='voucher_institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='voucher_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
