# Generated by Django 3.0.2 on 2023-02-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0030_auto_20230206_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='barcode',
        ),
    ]
