# Generated by Django 3.0.2 on 2023-02-06 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0031_remove_specimen_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.TargetSpecies', verbose_name='species'),
        ),
    ]
