# Generated by Django 3.0.2 on 2023-02-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0035_targetspecies_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('erga_long_list', 'ERGA Long List'), ('bge', 'BGE short list'), ('cbp', 'CBP'), ('erga_pilot', 'ERGA_Pilot'), ('wp11', 'WP11'), ('dtol', 'DTOL'), ('greece_hsp', 'GreeceHSp'), ('slovenia_hsp', 'SloveniaHSp'), ('spain_hsp', 'SpainHsp')], default='erga_long_list', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.RemoveField(
            model_name='targetspecies',
            name='tags',
        ),
        migrations.AddField(
            model_name='targetspecies',
            name='tags',
            field=models.ManyToManyField(default='ERGA_Long_List', to='status.Tag'),
        ),
    ]
