# Generated by Django 3.0.2 on 2023-02-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0036_auto_20230207_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Recipe name')),
                ('ont_target', models.BigIntegerField(blank=True, null=True, verbose_name='ONT target')),
                ('hifi_target', models.BigIntegerField(blank=True, null=True, verbose_name='HiFi target')),
                ('hic_target', models.BigIntegerField(blank=True, null=True, verbose_name='Hi-C target')),
                ('short_target', models.BigIntegerField(blank=True, null=True, verbose_name='Short read target')),
            ],
            options={
                'verbose_name_plural': 'recipes',
            },
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='hic_target',
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='hifi_target',
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='ont_target',
        ),
        migrations.RemoveField(
            model_name='sequencing',
            name='short_target',
        ),
    ]
