# Generated by Django 3.0.2 on 2023-02-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0039_auto_20230209_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
