# Generated by Django 3.0.2 on 2023-02-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0040_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.UserProfile', verbose_name='author')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.TargetSpecies', verbose_name='species')),
            ],
        ),
    ]
