# Generated by Django 3.0.2 on 2023-02-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0041_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyteam',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_team_lead', to='status.UserProfile'),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='genomic_sample_status',
            field=models.CharField(choices=[('None', 'None'), ('Long_Listed', 'Long_Listed'), ('Collecting', 'Collecting'), ('Resampling', 'Resampling'), ('COPO', 'COPO'), ('Submitted', 'Submitted'), ('Issue', 'Issue')], default='None', help_text='Status', max_length=12),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='rna_sample_status',
            field=models.CharField(choices=[('None', 'None'), ('Long_Listed', 'Long_Listed'), ('Collecting', 'Collecting'), ('Resampling', 'Resampling'), ('COPO', 'COPO'), ('Submitted', 'Submitted'), ('Issue', 'Issue')], default='None', help_text='Status', max_length=12),
        ),
        migrations.CreateModel(
            name='StatusUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(help_text='Process', max_length=30)),
                ('status', models.CharField(help_text='Status', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.TargetSpecies', verbose_name='species')),
            ],
            options={
                'verbose_name_plural': 'status_updates',
            },
        ),
    ]
