# Generated by Django 3.0.2 on 2023-02-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0042_auto_20230218_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdates',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.TargetSpecies', verbose_name='species'),
        ),
    ]
