# Generated by Django 3.0.2 on 2023-02-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0043_auto_20230218_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusUpdates',
            new_name='StatusUpdate',
        ),
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'verbose_name_plural': 'status updates'},
        ),
    ]
