# Generated by Django 3.0.2 on 2023-02-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0044_auto_20230218_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionteam',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_team_lead', to='status.UserProfile'),
        ),
        migrations.AlterField(
            model_name='collectionteam',
            name='members',
            field=models.ManyToManyField(null=True, to='status.UserProfile'),
        ),
    ]
