# Generated by Django 3.0.2 on 2023-02-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0045_auto_20230221_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_team_lead', to='status.UserProfile'),
        ),
        migrations.AlterField(
            model_name='collectionteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='status.UserProfile'),
        ),
    ]
