# Generated by Django 3.0.2 on 2023-02-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0046_auto_20230221_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionteam',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
