# Generated by Django 3.0.2 on 2023-02-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0048_auto_20230221_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Annotating', 'Annotating'), ('Done', 'Done'), ('Sent', 'Sent'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='communityannotation',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Annotating', 'Annotating'), ('Done', 'Done'), ('Sent', 'Sent'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='curation',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Curating', 'Curating'), ('Done', 'Done'), ('Sent', 'Sent'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='genomic_sample_status',
            field=models.CharField(choices=[('Not collected', 'Not collected'), ('Long List', 'Long List'), ('Collecting', 'Collecting'), ('Resampling', 'Resampling'), ('COPO', 'COPO'), ('Submitted', 'Submitted'), ('Issue', 'Issue')], default='Not collected', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='rna_sample_status',
            field=models.CharField(choices=[('Not collected', 'Not collected'), ('Long List', 'Long List'), ('Collecting', 'Collecting'), ('Resampling', 'Resampling'), ('COPO', 'COPO'), ('Submitted', 'Submitted'), ('Issue', 'Issue')], default='Not collected', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='genomic_seq_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Received', 'Received'), ('Extracted', 'Extracted'), ('Sequencing', 'Sequencing'), ('TopUp', 'TopUp'), ('External', 'External'), ('Submitted', 'Submitted'), ('Done', 'Done'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='hic_seq_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Received', 'Received'), ('Extracted', 'Extracted'), ('Sequencing', 'Sequencing'), ('TopUp', 'TopUp'), ('External', 'External'), ('Submitted', 'Submitted'), ('Done', 'Done'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='rna_seq_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Received', 'Received'), ('Extracted', 'Extracted'), ('Sequencing', 'Sequencing'), ('TopUp', 'TopUp'), ('External', 'External'), ('Submitted', 'Submitted'), ('Done', 'Done'), ('Issue', 'Issue')], default='Waiting', help_text='Status', max_length=20),
        ),
    ]
