# Generated by Django 3.0.2 on 2023-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0049_auto_20230222_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetspecies',
            name='listed_species',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
    ]
