# Generated by Django 3.0.2 on 2023-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0052_auto_20230302_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='leftover',
            field=models.CharField(choices=[('None', 'None'), ('DNA', 'DNA'), ('Tissue', 'Tissue'), ('Both', 'Both')], default='None', help_text='Leftover sample', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='leftover_biobanking_institution',
            field=models.CharField(blank=True, default='LIB', max_length=200, null=True, verbose_name='Biobanking destination for leftovers'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='biobanking_institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
