# Generated by Django 3.0.2 on 2023-03-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0053_auto_20230302_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='leftover_biobanking_institution',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='biobanking_institution',
        ),
        migrations.AddField(
            model_name='sample',
            name='leftover_biobanking_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.BiobankingTeam', verbose_name='biobanking team'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='biobanking_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.BiobankingTeam', verbose_name='biobanking team'),
        ),
    ]
