# Generated by Django 3.0.2 on 2023-01-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20230112_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genometeam',
            name='annotation_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.AnnotationTeam', verbose_name='annotation team'),
        ),
        migrations.AlterField(
            model_name='genometeam',
            name='assembly_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.AssemblyTeam', verbose_name='assembly team'),
        ),
        migrations.AlterField(
            model_name='genometeam',
            name='collection_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.CollectionTeam', verbose_name='collection team'),
        ),
        migrations.AlterField(
            model_name='genometeam',
            name='sample_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Person', verbose_name='sample_coordinator'),
        ),
        migrations.AlterField(
            model_name='genometeam',
            name='sequencing_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.SequencingTeam', verbose_name='sequencing team'),
        ),
        migrations.AlterField(
            model_name='genometeam',
            name='taxonomy_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.TaxonomyTeam', verbose_name='taxonomy team'),
        ),
    ]
