# Generated by Django 3.0.2 on 2023-01-13 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20230113_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencingteam',
            name='reception',
        ),
        migrations.AddField(
            model_name='annotationteam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotationteam',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collectionteam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionteam',
            name='members',
            field=models.ManyToManyField(to='status.Person'),
        ),
        migrations.AddField(
            model_name='collectionteam',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curationteam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curationteam',
            name='members',
            field=models.ManyToManyField(to='status.Person'),
        ),
        migrations.AddField(
            model_name='curationteam',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sequencingteam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequencingteam',
            name='members',
            field=models.ManyToManyField(to='status.Person'),
        ),
        migrations.AddField(
            model_name='sequencingteam',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submissionteam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissionteam',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taxonomyteam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxonomyteam',
            name='members',
            field=models.ManyToManyField(to='status.Person'),
        ),
        migrations.AddField(
            model_name='taxonomyteam',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='VoucheringTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchering_team_lead', to='status.Person')),
                ('members', models.ManyToManyField(to='status.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SampleHandlingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_handling_team_lead', to='status.Person')),
                ('members', models.ManyToManyField(to='status.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_team_lead', to='status.Person')),
                ('members', models.ManyToManyField(to='status.Person')),
            ],
            options={
                'verbose_name_plural': 'extraction teams',
            },
        ),
        migrations.CreateModel(
            name='CommunityAnnotationTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_annotation_team_lead', to='status.Person')),
                ('members', models.ManyToManyField(to='status.Person')),
            ],
            options={
                'verbose_name_plural': 'annotation teams',
            },
        ),
        migrations.CreateModel(
            name='BarcodingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcoding_team_lead', to='status.Person')),
                ('members', models.ManyToManyField(to='status.Person')),
            ],
        ),
        migrations.AddField(
            model_name='genometeam',
            name='barcoding_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.BarcodingTeam', verbose_name='barcoding team'),
        ),
        migrations.AddField(
            model_name='genometeam',
            name='community_annotation_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.CommunityAnnotationTeam', verbose_name='community annotation team'),
        ),
        migrations.AddField(
            model_name='genometeam',
            name='extraction_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.ExtractionTeam', verbose_name='nucleic acid extraction team'),
        ),
        migrations.AddField(
            model_name='genometeam',
            name='sample_handling_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.SampleHandlingTeam', verbose_name='sample handling team'),
        ),
        migrations.AddField(
            model_name='genometeam',
            name='vouchering_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.VoucheringTeam', verbose_name='vouchering team'),
        ),
    ]
