# Generated by Django 3.0.2 on 2023-01-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_auto_20230123_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RemoveField(
            model_name='assemblyproject',
            name='team',
        ),
    ]
