# Generated by Django 3.0.2 on 2023-01-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_communityannotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencing',
            name='team',
        ),
    ]
