# Generated by Django 3.0.2 on 2023-01-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0012_remove_sequencing_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orcid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='ORCID'),
        ),
    ]
