# Generated by Django 3.0.2 on 2023-01-30 13:04

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_userprofile_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lead',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('genome_team_coordinator', 'Genome Team Coordinator'), ('sample_coordinator', 'Sample Coordinator'), ('collection_team', 'Collection Team'), ('taxonomy_team', 'Taxonomy Team'), ('vouchering_team', 'Vouchering Team'), ('barcoding_team', 'Barcoding Team'), ('sequencing_team', 'Sequencing Team'), ('assembly_team', 'Assembly Team'), ('community_annotation_team_', 'Community Annotation Team'), ('annotation_team', 'Annotation Team')], max_length=176, null=True),
        ),
    ]
