# Generated by Django 3.0.2 on 2023-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0014_auto_20230130_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='Joe', max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='Smith', max_length=30, null=True, verbose_name='Last Name'),
        ),
    ]
