# Generated by Django 3.0.2 on 2023-01-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0015_auto_20230130_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
    ]
