# Generated by Django 3.0.2 on 2023-01-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0016_auto_20230130_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
