# Generated by Django 3.0.2 on 2023-01-30 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0017_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('genome_team_coordinator', 'Genome Team Coordinator'), ('sample_coordinator', 'Sample Coordinator'), ('collection_team', 'Collection Team'), ('taxonomy_team', 'Taxonomy Team'), ('vouchering_team', 'Vouchering Team'), ('barcoding_team', 'Barcoding Team'), ('sequencing_team', 'Sequencing Team'), ('assembly_team', 'Assembly Team'), ('community_annotation_team_', 'Community Annotation Team'), ('annotation_team', 'Annotation Team')], max_length=176, null=True)),
                ('orcid', models.CharField(blank=True, max_length=60, null=True, verbose_name='ORCID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
